version: '3.1'

services:
    nginx:
        image: nginx:latest
        depends_on:
            - php
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./:/app
        ports:
            - "80:80"

    php:
        build:
            context: .
            dockerfile: PHP.Dockerfile
        volumes:
            - ./:/app
        env_file:
            - .env

    mysql:
        image: mariadb:latest
        volumes:
            - mysqldata:/var/lib/mysql
        env_file:
            - .env
        ports:
            - 3306:3306

    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - 8080:80
        environment:
            - PMA_HOST=mysql

    ratchet:
        build:
            context: .
            dockerfile: Ratchet.Dockerfile
        volumes:
            - ./:/app
        env_file:
            - .env
        ports:
            - "8082:8082"

volumes:
    mysqldata: {}
